### ISSUE TITLE
Continuous Compilation isn't triggering on file changes

### ISSUE THREAD

**Issue by SelfishOlex** [MolecularMatters/lpp_public#10]
Platform: Windows 11
Live++ 2.5.0 (same issue on 2.4.x)

My project preferences:
![image](https://github.com/MolecularMatters/lpp_public/assets/5432499/b6f32406-4303-4086-9f3b-b74cbe9f3ee5)

Broke view of the executable to confirm matching source folder.
![image](https://github.com/MolecularMatters/lpp_public/assets/5432499/2341c3ef-e413-4043-985e-7e399478d358)

I'm not seeing any log entries on file changes. (Shortcut invocation works.)

What can I do to diagnose this issue?

Thanks!

**Comment by tivolo** [comment]
How do you load these project preferences?
Can you confirm that they are picked up correctly by the Broker?
You should see a corresponding message (or error) in the Broker UI log.

**Comment by SelfishOlex** [comment]
Hmm, I am not doing anything to load project preferences. That must be it then.

**Comment by SelfishOlex** [comment]
I'll give LppCreateDefaultAgentWithPreferencesFromFile a try. That looks right. Currently, I'm just calling LppCreateDefaultAgent.

**Comment by SelfishOlex** [comment]
Boom, that works. Thanks!

**Comment by tivolo** [comment]
Glad to hear you got it working!
