### ISSUE TITLE
Feature request: pass custom arguments string in Agent::Restart()

### ISSUE THREAD

**Issue by Pomakhin** [MolecularMatters/lpp_public#11]
Hello
In our use case, we have to restart game process when switching between play and editor mode. And if you already have a patched executable, it's very convenient to use Agent::Restart() method. The only problem is that in editor mode, we need to restart the process with a different set of arguments. And it looks like currently it's not possible. Can you please consider adding it in one of the future versions? 

Best regards, 
Mikhail

**Comment by MolecularMatters** [comment]
Hi Mikhail,

That sounds like a useful addition.
We'll consider it for the next update and will update this feature request once it's available.

**Comment by MolecularMatters** [comment]
This has shipped in today's 2.7.0 update: https://liveplusplus.tech/releases.html

**Comment by Pomakhin** [comment]
Thank you very much! We'll update to it and try it out asap
