### ISSUE TITLE
Live++ crash reports can fill up your storage over time

### ISSUE THREAD

**Issue by Shimmen** [MolecularMatters/lpp_public#12]
Hi,

Live++ crash dumps keep filling up our PCs. From the look of things we generate a few of them each day when using our application, and each of them can get quite large (up to a few GBs). I'm guessing this is abnormal behavior, but both our application & the Live++ Broker keeps working fine, so I'm not exactly sure what is crashing and generating the dump files.

It's probably not a bad idea to figure out what's causing these crash dumps in the first place, but considering the size of the dumps and the potential rate they are produced in, I think it'd be good for Live++ to track these and delete old ones. This would ensure Live++ does not completely full up the PC storage, like it has done in my case here (and many times before & for other's too).

![livepp-crash-dumps](https://github.com/user-attachments/assets/314feece-9b74-4b25-85a1-b1b7d36e4d72)

We're on a somewhat old version (2.4.1) but we can't find anything relevant in the change logs. Let us know if you think upgrading would resolve this.

Thanks!

Kind regards,
Simon Moos

**Comment by tivolo** [comment]
Thank you very much for reporting this Simon.

This is definitely very abnormal behaviour, and it seems like the Live++ Broker produces crash dumps at a rate of one every minute (!), yet keeps on running as you mentioned.

I'd suggest upgrading to the latest 2.7.2 and see if this goes away.
But in any case, can you make one of these crash dumps available to us? It's very, very odd that the Broker would produce a crash dump but keep on running as if nothing happened and I'd absolutely like to investigate this.

**Comment by Shimmen** [comment]
Hi! I'm happy to send a crash dump to you, but would rather do it in a confidential way (just in case there's any info about our exe/symbols inside). Please just let me know where to send.

Will also update to the latest now.

Thanks!

**Comment by tivolo** [comment]
Absolutely.
Please reach out to us at support@molecular-matters.com.

Thanks!

**Comment by MolecularMatters** [comment]
This was caused by portable USB drives spontaneously disconnecting every now and then, causing an EXCEPTION_IN_PAGE_ERROR error that was caught by the exception handler in the Broker.

In the next 2.8.0 update, these exceptions will no longer cause a dump to be written, but will output a warning to the user instead.
