### ISSUE TITLE
Feature request: filtering/ordering by optimization status in the Broker

### ISSUE THREAD

**Issue by linkablonk** [MolecularMatters/lpp_public#4]
**Scenario**: I would like to keep track of which compilands I have toggled optimizations on for easier batch-reoptimization
**Proposed feature**: An option to see all deoptimized compilands at a glance would help, whether it is through a checkbox, a column sort or a keyword in the filter box.

**Comment by MolecularMatters** [comment]
What do you think about this:
![image](https://user-images.githubusercontent.com/61518974/229799157-bd297959-008e-4b54-a76b-014c0ebab3d7.png)

The "View" and "Actions" buttons should be self-explanatory.
The idea is to add an entry to the context menu for "Queue for deoptimization", which will queue selected compilands for later.
Queued compilands will get a separate icon in the compilands view and can all be deoptimized by clicking "Deoptimize queued".

Once you're done with deoptimizing your compilands and want to go back to their original state, click "Reoptimize all".

The views should allow you to toggle the state of seeing compilands in their original state, compilands that are deoptimized, and compilands that are currently queued.

**Comment by linkablonk** [comment]
Looks pretty reasonable ! It makes sense that #5 and this one would work together.
The "Reoptimize all" button seems to be a kind of macro for "Show deoptimized" + "Toggle optimizations", which may or may not be optimal UX, but it works. As for "Deoptimize queued", it fits the bill to a T. 

edit: the one issue I could see with the queue is that it could be construed as working two ways, so there should probably be an indicator that it is a "deoptimization" queue - or maybe it should be made generic.
Also, I suppose hitting "Reoptimize all" would clear the deoptimization queue... Unless we'd intend for it to act as a tool for switching between exclusive sets of deoptimized files.

edit 2: regardless, I like it.

**Comment by MolecularMatters** [comment]
This has shipped in 2.1.4 today: https://liveplusplus.tech/releases.html

**Comment by linkablonk** [comment]
> This has shipped in 2.1.4 today: https://liveplusplus.tech/releases.html

Tried it today, it works ! Thanks !
