### ISSUE TITLE
Broken feature request: queuing "toggle optimizations" requests

### ISSUE THREAD

**Issue by linkablonk** [MolecularMatters/lpp_public#5]
**Scenario**: toggling optimizations for multiple compilands in contexts with large amounts of compilands requires using a filter, toggling optimizations on a bunch of compilands, waiting until compilation is done, and then repeating with a different filter

**Proposed feature**: using a compilation queue, so that I can send a bunch of compilands for deoptimizations. Deoptimization does not have to start straight away, there could be an option for toggling immediately and another for queuing, and then for starting processing the queue.

**Comment by MolecularMatters** [comment]
This has shipped in 2.1.4 today: https://liveplusplus.tech/releases.html
