### ISSUE TITLE
Feature Request: Hot-Restart global shortcut

### ISSUE THREAD

**Issue by Scorr** [MolecularMatters/lpp_public#8]
Hot-Reload has a setting "shortcut to invoke" that executes from anywhere. It'd be nice if Hot-Restart also had this so we can restart without focusing the live++ broker window.

**Comment by MolecularMatters** [comment]
That sounds like a useful addition.
Any particular shortcut you had in mind to be set as a default?

**Comment by Scorr** [comment]
I personally have hotreload bound to ctrl+B because it's easy to press and does not generally conflict with other things like most ctrl+button combos in left hand area. So I'd probably bind hotrestart to something like ctrl+shift+B, but I'm not sure if it's the best default for everyone.

ctrl+R or ctrl+shift+R would probably be good as well.

**Comment by MolecularMatters** [comment]
This has been implemented and will ship in the next update.

**Comment by Scorr** [comment]
wow so fast
amazing, thanks!

**Comment by MolecularMatters** [comment]
This has shipped in Live++ 2.4.0:
https://liveplusplus.tech/releases.html

Thanks again for the suggestion!
